# Generated by Django 3.1.3 on 2020-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageExtractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='path',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
