# Generated by Django 3.1.3 on 2020-11-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageExtractor', '0002_request_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='path',
            field=models.FilePathField(null=True),
        ),
    ]
